// nether_route: ONE covered way through the Nether made of several legs (stairs and straight roads) - the route to the fortress.
//
// WHY ONE BLUEPRINT (top model 09-21): two blueprints that meet at a corner disagree about the corner - one says "wall", the other
// "walkway" - and two jobs that each build their own would dig and refill the same cells for ever (`build_runaway`, 09-21 0x:xxZ).
// Here every leg is generated by its own blueprint (`nether_road`, `nether_stair`) and the cells are MERGED: a cell any leg needs
// clear is clear (the corner opens), a torch only goes where no leg needs rock. Every cell carries `seq` = its distance along the
// route from the start, so a squad works the route from the hub outwards and the head of the work is a number on the board.
//
// params: legs = [{ kind:'road'|'stair', from:[x,y,z], bearing, length (road) | toY + run (stair), reverse, noTorch }]
//   reverse:true  the leg is WALKED against its blueprint's order (a stair that climbs away from the start is a stair blueprint
//                 descending towards it) - only the seq numbering turns round.
//   noTorch:true  no torches on this leg (a leg that ends beside a blaze spawner must not light its spawn cells).
// meta: { path: [[x,y,z] feet cell per seq], box, end, length, legs }
const road = require('./nether_road')
const stair = require('./nether_stair')
const DIRS = { 'x+': [1, 0], 'x-': [-1, 0], 'z+': [0, 1], 'z-': [0, -1] }

function legCells (L) {
  const o = { x: L.from[0], y: L.from[1], z: L.from[2] }
  const [ax, az] = DIRS[L.bearing] || DIRS['x+']
  const cells = L.kind === 'stair' ? stair(o, { bearing: L.bearing, toY: L.toY, run: L.run || 1 }) : road(o, { bearing: L.bearing, length: L.length })
  // the index along the leg = the distance along the bearing from the leg's origin
  let n = 0
  for (const c of cells) { c.i = (c.x - o.x) * ax + (c.z - o.z) * az; if (c.i + 1 > n) n = c.i + 1 }
  // the feet cell of each index: the interior l = 0 cell, at the leg's floor + 1
  const feet = []
  for (let i = 0; i < n; i++) {
    const y = L.kind === 'stair' ? L.from[1] - Math.floor(i / (L.run || 1)) : L.from[1]
    feet.push([L.from[0] + ax * i, y, L.from[2] + az * i])
  }
  return { cells, n, feet }
}

function build (legs) {
  const merged = new Map(); const path = []; let base = 0
  for (const L of legs) {
    const { cells, n, feet } = legCells(L)
    const seqOf = i => base + (L.reverse ? n - 1 - i : i)
    for (const c of cells) {
      if (c.block === 'torch' && L.noTorch) continue
      const k = c.x + ',' + c.y + ',' + c.z
      const seq = seqOf(c.i); const prev = merged.get(k)
      const cell = { x: c.x, y: c.y, z: c.z, block: c.block, seq }
      if (c.needs) cell.needs = c.needs
      if (!prev) { cell.saw = { [c.block]: 1 }; merged.set(k, cell); continue }
      // a cell any leg needs clear is clear (the corner opens); a torch stands in a walkway cell, never where a leg needs rock
      prev.saw[c.block] = 1; prev.seq = Math.min(prev.seq, seq)
      if (c.needs) prev.needs = c.needs
      const w = prev.saw
      prev.block = (w.air || w.torch) ? ((w.torch && !w.stone) ? 'torch' : 'air') : 'stone'
    }
    const fs = L.reverse ? feet.slice().reverse() : feet
    for (const f of fs) path.push(f)
    base += n
  }
  return { cells: [...merged.values()].map(c => { delete c.saw; if (c.block !== 'torch') delete c.needs; return c }), path }
}

module.exports = (o, p = {}) => build(Array.isArray(p.legs) ? p.legs : []).cells
module.exports.meta = (o, p = {}) => {
  const legs = Array.isArray(p.legs) ? p.legs : []
  const { cells, path } = build(legs)
  const xs = cells.map(c => c.x); const zs = cells.map(c => c.z)
  return {
    legs: legs.length, length: path.length, path, end: path[path.length - 1] || null,
    box: cells.length ? [Math.min(...xs) - 2, Math.min(...zs) - 2, Math.max(...xs) + 2, Math.max(...zs) + 2] : null
  }
}
