#!/bin/bash
# ops/modes-pack.sh — (re)write the `modes` datapack into the live world and /reload. ONE source for what humans can do here, op-less:
#   /trigger tp = clickable list of ALL online players (bots, guests, other spectators), click = jump there (owner 09-20); /trigger tp set <1000+id> = the same by number (what a click on a bot's chat line sends)
#   everybody outside teams `army`/`guests` is a SPECTATOR (forced every tick) · GUESTS below play SURVIVAL (owner's order from the terminal only) · (chat-line click)
#   /trigger prank = a clickable menu of small PRANKS (owner 09-19: "見てるだけだとつまらない"): a mob on the surface under the spectator,
#   only within 48 blocks of a bot or a survival guest. Brakes (owner 09-20: "同時上限とクリーパー間隔だけでいい"): NO cooldown; at most 20 prank mobs alive (owner 09-20: "40体多いかも") AND at most 2 per survival player within 48 blocks (a lone bot never faces a legion); a creeper every 30 s per player and never within 16 blocks of a survival player (owner 09-20: no point-blank creepers; it has to walk up); [HORDE x10] = a legion in one click;
#   every prank is announced to everybody. Prank mobs carry the tag `prank` and despawn like any mob.
# survival guests = ANOTHER TEAM'S BOTS, allowed by the owner from the terminal (09-19). Who they are is LOCAL config, not code:
# server/guests.json {tag,label,names[]} (untracked; no file = no guests). Their names are IP-pinned in server/plugins/BotGuard/config.yml; gamerule pvp is false.
W=/root/workspace
GJ=$W/server/guests.json; gq() { [ -e $GJ ] && node -p "const g=require('$GJ');$1" || echo "$2"; }
GUESTS="$(gq "g.names.join(' ')" '')"; GTAG="$(gq 'g.tag' 'GUEST')"; GLABEL="$(gq 'g.label' 'guest bots')"
S=$W/server; D=$S/world/datapacks/modes; F=$D/data/modes/function
mkdir -p $D/data/minecraft/tags/function $F
cat > $D/pack.mcmeta <<'P'
{"pack":{"description":"humans are spectators; /trigger tp, dim, prank","min_format":94,"max_format":[107,1]}}
P
echo '{"values":["modes:load"]}' > $D/data/minecraft/tags/function/load.json
echo '{"values":["modes:tick"]}' > $D/data/minecraft/tags/function/tick.json
cat > $F/load.mcfunction <<'P'
scoreboard objectives remove goto
scoreboard objectives add prank trigger
scoreboard objectives add prank_cd dummy
scoreboard objectives add prank_sk dummy
scoreboard objectives add prank_hd dummy
scoreboard objectives add prank_age dummy
scoreboard objectives add tp trigger
scoreboard objectives remove nether
scoreboard objectives add dim trigger
scoreboard objectives add nk trigger
scoreboard objectives add pid dummy
execute unless score #next pid matches 100.. run scoreboard players set #next pid 100
scoreboard players set #20 prank_cd 20
scoreboard players set #4 prank_cd 2
P
# the guests are ANOTHER TEAM'S BOTS (owner 09-20: "別のチームのbotです、異なるロール付けて" / "もっと短くして"): their own tag in chat/tab/nameplate, gold,
# so nobody takes them for ours ([BOT], aqua) or for a human spectator; our chat daemon does not talk to them (bots/chatter.js other_bots).
node $W/bots/rcon.js "team add guests" "team modify guests color gold" "team modify guests displayName {\"text\":\"$GLABEL\"}" "team modify guests prefix {\"text\":\"[$GTAG] \",\"color\":\"gold\"}" "team modify guests friendlyFire false" "gamerule pvp false" >/dev/null
for n in $GUESTS; do node $W/bots/rcon.js "team join guests $n" >/dev/null; done
node -e "
const r=Object.keys(require('$W/bots/assignments.json'));let s='# generated by ops/modes-pack.sh. Humans = everybody outside team army: always spectators. Bots are never touched.\n'
const H='scores={pid=100..},team=!guests' // humans who only watch: bots are pid 1..N (set by NAME at load, works offline), everybody else gets 101+
s+='execute as @a unless score @s pid matches 1.. run function modes:newpid\n'
// tag free = the OWNER while he holds a temporary op from the terminal (09-20): not forced back to spectator; given and taken ONLY by rcon from the terminal (tag fa0311 add free / remove), never on a chat request
s+='gamemode spectator @a['+H+',tag=!free,gamemode=!spectator]\ngamemode survival @a[team=guests,gamemode=!survival]\nscoreboard players enable @a['+H+'] prank\n'
// EVERY player has an id (objective pid): bots = roster number 1..N (fixed at load, so the chat-line click of the bots - trigger tp set 1000+N - keeps working),
// everybody else gets the next free number from 101 on first sight. trigger tp = clickable list of ALL online players, trigger tp set 1000+id = jump.
s+='scoreboard players enable @a['+H+'] tp\n'
s+='scoreboard players enable @a['+H+'] nk\nexecute as @a[team=!guests,scores={pid=100..,nk=1..}] run function modes:nk_go\nscoreboard players set @a[scores={nk=1..}] nk 0\n'
s+='scoreboard players enable @a['+H+'] dim\nexecute as @a[team=!guests,scores={pid=100..,dim=1..}] at @s run function modes:dim_go\nscoreboard players set @a[scores={dim=1..}] dim 0\n'
s+='execute as @a[team=!guests,scores={pid=100..,tp=1..999}] run function modes:tp_menu\nexecute as @a[team=!guests,scores={pid=100..,tp=1000..}] run function modes:tp_go\nscoreboard players set @a[scores={tp=1..}] tp 0\n'
let L=require('fs').readFileSync('$F/load.mcfunction','utf8');r.forEach((n,i)=>{L+='scoreboard players set '+n+' pid '+(i+1)+'\n'});require('fs').writeFileSync('$F/load.mcfunction',L)
s+='scoreboard players remove @a[scores={prank_sk=1..}] prank_sk 1\nscoreboard players remove @a[scores={prank_hd=1..}] prank_hd 1\nscoreboard players add @e[tag=prank] prank_age 1\nexecute as @e[tag=prank,scores={prank_age=3600..}] at @s run tp @s ~ -400 ~\n'
s+='scoreboard players remove @a[scores={prank_cd=1..}] prank_cd 1\nexecute if score #global prank_cd matches 1.. run scoreboard players remove #global prank_cd 1\n'
s+='execute as @a[team=!guests,scores={pid=100..,prank=1..}] at @s run function modes:prank\nscoreboard players set @a[scores={prank=1..}] prank 0\n'
require('fs').writeFileSync('$F/tick.mcfunction',s)"
cat > $F/newpid.mcfunction <<'P'
scoreboard players add #next pid 1
scoreboard players operation @s pid = #next pid
P
rm -f $F/goto_go.mcfunction   # ONE trigger (owner 09-20: "tpとgotoって一本化するの難しいの？" - it was not; goto was simply the older one): /trigger tp = menu, /trigger tp set 1000+id = jump
cat > $F/tp_go.mcfunction <<'P'
scoreboard players operation #want pid = @s tp
scoreboard players remove #want pid 1000
function modes:go
P
cat > $F/go.mcfunction <<'P'
# as the spectator who asked: jump to the online player whose pid = #want (any dimension)
tag @s add tp_me
scoreboard players set #ok pid 0
execute as @a[tag=!tp_me] if score @s pid = #want pid run function modes:go2
execute if score #ok pid matches 0 run tellraw @s {"text":"that player is not online right now - /trigger tp shows who is","color":"gray"}
tag @s remove tp_me
P
cat > $F/go2.mcfunction <<'P'
tp @a[tag=tp_me,limit=1] @s
scoreboard players set #ok pid 1
P
cat > $F/tp_menu.mcfunction <<'P'
# as the spectator who asked: one clickable line per online player - humans and guests first, then the bots
tag @s add tp_me
tellraw @s [{"text":"TP ","color":"gold","bold":true},{"text":"click [tp] to jump to a player","color":"gray","bold":false}]
execute as @a[tag=!tp_me,scores={pid=100..}] run function modes:tp_line
execute as @a[tag=!tp_me,scores={pid=1..99}] run function modes:tp_line
tag @s remove tp_me
P
cat > $F/tp_line.mcfunction <<'P'
scoreboard players operation #t pid = @s pid
scoreboard players add #t pid 1000
execute store result storage modes:tmp id int 1 run scoreboard players get #t pid
function modes:tp_line2 with storage modes:tmp
P
cat > $F/tp_line2.mcfunction <<'P'
$tellraw @a[tag=tp_me] [{"text":" [tp] ","color":"aqua","click_event":{"action":"run_command","command":"/trigger tp set $(id)"}},{"selector":"@s"}]
P
cat > $F/prank.mcfunction <<'P'
# as + at the spectator, prank >= 1.  1 (plain `/trigger prank`) = menu, 11.. = the pranks. TUNED 09-20 (owner: "prankのパラメータ調整しといて"; one spectator dropped 65 skeletons + 15 hordes in a morning,
# 13 builders shot in 2 h while the owner complained about slow work): cap 12 alive (2 per bot nearby), half health, 3 min lifetime, intervals skeleton 15 s / creeper 30 s / horde 90 s, horde = 6 zombies + 1 skeleton + 3 spiders.
execute if score @s prank matches 1..10 run tellraw @s [{"text":"PRANK ","color":"gold","bold":true},{"text":"[zombie] ","color":"green","click_event":{"action":"run_command","command":"/trigger prank set 11"}},{"text":"[skeleton] ","color":"white","click_event":{"action":"run_command","command":"/trigger prank set 12"}},{"text":"[spider] ","color":"dark_red","click_event":{"action":"run_command","command":"/trigger prank set 13"}},{"text":"[creeper] ","color":"dark_green","click_event":{"action":"run_command","command":"/trigger prank set 14"}},{"text":"[HORDE x10] ","color":"red","bold":true,"click_event":{"action":"run_command","command":"/trigger prank set 17"}},{"text":"[chickens] ","color":"yellow","click_event":{"action":"run_command","command":"/trigger prank set 15"}},{"text":"[firework]","color":"light_purple","click_event":{"action":"run_command","command":"/trigger prank set 16"}}]
execute if score @s prank matches 1..10 run tellraw @s {"text":"lands on the surface under you, only within 48 blocks of a bot or a survival guest. At most 2 prank mobs per bot nearby (12 in all), they have half health and vanish after 3 min. Intervals: skeleton 15 s, creeper 30 s, horde 90 s (5+ bots).","color":"gray"}
execute if score @s prank matches 1..10 run return 0
execute unless score @s prank matches 11..17 run return 0
execute unless entity @a[gamemode=survival,distance=..48] run return run tellraw @s {"text":"nobody in survival within 48 blocks - fly closer","color":"gray"}
execute store result score #n prank_cd if entity @e[tag=prank]
execute if score #n prank_cd matches 12.. run return run tellraw @s {"text":"12 prank mobs are still alive - let the bots deal with them first","color":"gray"}
# FAIR FIGHT (owner 09-20: "1人しかいないとこに40体だされたらやばい"): the cap is LOCAL - at most 4 prank mobs per survival player within 48 blocks
# (one lone bot: 4; a squad of ten: 40). A horde of 10 needs room for 10, i.e. at least 3 players around.
execute store result score #near prank_cd if entity @e[tag=prank,distance=..48]
execute store result score #room prank_cd if entity @a[gamemode=survival,distance=..48]
scoreboard players operation #room prank_cd *= #4 prank_cd
scoreboard players operation #room prank_cd -= #near prank_cd
execute if score @s prank matches 11..16 if score #room prank_cd matches ..0 run return run tellraw @s {"text":"enough for the few who stand here (2 prank mobs per bot nearby) - find a bigger crowd","color":"gray"}
execute if score @s prank matches 17 if score #room prank_cd matches ..9 run return run tellraw @s {"text":"a horde needs a crowd: at least 5 bots within 48 blocks and room for 10 more mobs (2 per bot)","color":"gray"}
scoreboard players operation #s prank_cd = @s prank_cd
scoreboard players operation #s prank_cd /= #20 prank_cd
execute if score @s prank matches 14 if entity @a[gamemode=survival,distance=..16] run return run tellraw @s {"text":"too close: a creeper needs 16 blocks of distance to every bot or guest - drop it further away and let it walk","color":"gray"}
execute if score @s prank matches 14 if score @s prank_cd matches 1.. run return run tellraw @s [{"text":"creeper cooldown: ","color":"gray"},{"score":{"name":"#s","objective":"prank_cd"}},{"text":" s"}]
execute if score @s prank matches 14 run scoreboard players set @s prank_cd 600
execute if score @s prank matches 12 if score @s prank_sk matches 1.. run return run tellraw @s {"text":"skeleton interval: 15 s (arrows kill builders - 13 deaths in 2 h on 09-20)","color":"gray"}
execute if score @s prank matches 12 run scoreboard players set @s prank_sk 300
execute if score @s prank matches 17 if score @s prank_hd matches 1.. run return run tellraw @s {"text":"horde interval: 90 s","color":"gray"}
execute if score @s prank matches 17 run scoreboard players set @s prank_hd 1800
execute if score @s prank matches 11 positioned over world_surface run summon zombie ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1}}}
execute if score @s prank matches 12 positioned over world_surface run summon skeleton ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1},mainhand:{id:"minecraft:bow",count:1}}}
execute if score @s prank matches 13 positioned over world_surface run summon spider ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:8.0d}],Health:8f}
execute if score @s prank matches 14 positioned over world_surface run summon creeper ~ ~ ~ {Tags:["prank"]}
execute if score @s prank matches 15 positioned over world_surface run summon chicken ~ ~1 ~ {Tags:["prank"]}
execute if score @s prank matches 15 positioned over world_surface run summon chicken ~1 ~1 ~ {Tags:["prank"]}
execute if score @s prank matches 15 positioned over world_surface run summon chicken ~ ~1 ~1 {Tags:["prank"]}
execute if score @s prank matches 16 positioned over world_surface run summon firework_rocket ~ ~1 ~ {LifeTime:25,FireworksItem:{id:"minecraft:firework_rocket",count:1,components:{"minecraft:fireworks":{flight_duration:1,explosions:[{shape:"large_ball",colors:[I;16711680,16776960,65535]}]}}}}
execute if score @s prank matches 17 run function modes:horde
execute if score @s prank matches 11 run tellraw @a [{"text":"PRANK ","color":"gold"},{"selector":"@s"},{"text":" dropped a zombie near "},{"selector":"@p[gamemode=survival]"}]
execute if score @s prank matches 12 run tellraw @a [{"text":"PRANK ","color":"gold"},{"selector":"@s"},{"text":" dropped a skeleton near "},{"selector":"@p[gamemode=survival]"}]
execute if score @s prank matches 13 run tellraw @a [{"text":"PRANK ","color":"gold"},{"selector":"@s"},{"text":" dropped a spider near "},{"selector":"@p[gamemode=survival]"}]
execute if score @s prank matches 14 run tellraw @a [{"text":"PRANK ","color":"gold"},{"selector":"@s"},{"text":" dropped a CREEPER near "},{"selector":"@p[gamemode=survival]"}]
execute if score @s prank matches 15 run tellraw @a [{"text":"PRANK ","color":"gold"},{"selector":"@s"},{"text":" sent chickens to "},{"selector":"@p[gamemode=survival]"}]
execute if score @s prank matches 16 run tellraw @a [{"text":"PRANK ","color":"gold"},{"selector":"@s"},{"text":" lit a firework over "},{"selector":"@p[gamemode=survival]"}]
execute if score @s prank matches 17 run tellraw @a [{"text":"PRANK ","color":"red","bold":true},{"selector":"@s"},{"text":" sent a HORDE (6 zombies, 1 skeleton, 3 spiders) at "},{"selector":"@p[gamemode=survival]"}]
P
cat > $F/horde.mcfunction <<'P'
# a mob legion in one click: spread on the surface around the spectator's column (helmets: they do not burn by day)
execute positioned ~2 ~ ~ positioned over world_surface run summon zombie ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1}}}
execute positioned ~-2 ~ ~ positioned over world_surface run summon zombie ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1}}}
execute positioned ~ ~ ~2 positioned over world_surface run summon zombie ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1}}}
execute positioned ~ ~ ~-2 positioned over world_surface run summon zombie ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1}}}
execute positioned ~3 ~ ~3 positioned over world_surface run summon zombie ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1}}}
execute positioned ~-3 ~ ~-3 positioned over world_surface run summon zombie ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1}}}
execute positioned ~4 ~ ~-4 positioned over world_surface run summon skeleton ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:10.0d}],Health:10f,equipment:{head:{id:"minecraft:leather_helmet",count:1},mainhand:{id:"minecraft:bow",count:1}}}
execute positioned ~-4 ~ ~4 positioned over world_surface run summon spider ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:8.0d}],Health:8f}
execute positioned ~5 ~ ~ positioned over world_surface run summon spider ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:8.0d}],Health:8f}
execute positioned ~ ~ ~5 positioned over world_surface run summon spider ~ ~ ~ {Tags:["prank"],attributes:[{id:"minecraft:max_health",base:8.0d}],Health:8f}
P
# THE ARMY'S STORES: guests cannot OPEN or BREAK containers / furnaces / tables inside the base box - BotGuard plugin (`stores` in its config), verified 09-20 13:16Z with a test
# account (no window opens). The first answer, a datapack advancement that KILLED a guest on touch, is gone (owner: "空けられないようにするとか出来る？"): remove its files.
rm -rf $D/data/modes/advancement $F/guest_kill.mcfunction
# /trigger nk (owner 09-20, from the terminal: "nakasyou_bot を kill する trigger 作れる？" then "nk コマンド誰でも使えるようにして"): EVERY human spectator (never a guest, never an army
# bot) gets a clickable list of the guest team's bots that are online and kills the one clicked, or all of them - no op needed. Every use is announced with the name of who did it.
{ echo 'execute if score @s nk matches 1..9 run tellraw @s {"text":"KILL a guest bot:","color":"red","bold":true}'
  i=10; for n in $GUESTS; do
    echo "execute if score @s nk matches 1..9 if entity @a[name=$n] run tellraw @s {\"text\":\"  [$n]\",\"color\":\"gold\",\"click_event\":{\"action\":\"run_command\",\"command\":\"/trigger nk set $i\"}}"
    echo "execute if score @s nk matches $i run kill @a[name=$n]"
    echo "execute if score @s nk matches $i run tellraw @a [{\"selector\":\"@s\",\"color\":\"red\"},{\"text\":\" removed $n\",\"color\":\"gray\"}]"
    i=$((i+1)); done
  echo 'execute if score @s nk matches 1..9 run tellraw @s {"text":"  [ALL guests]","color":"red","click_event":{"action":"run_command","command":"/trigger nk set 99"}}'
  echo 'execute if score @s nk matches 99 run kill @a[team=guests]'
  echo 'execute if score @s nk matches 99 run tellraw @a [{"selector":"@s","color":"red"},{"text":" removed every guest bot","color":"gray"}]'
} > $F/nk_go.mcfunction
node $W/bots/rcon.js "reload" >/dev/null; sleep 2
# ORDER MATTERS: the reloaded tick function recognises bots by their pid score; only THEN may the bots leave the old `army` team - with the old
# function still loaded a bot outside team army would be forced into spectator.
# ONE TEAM PER BOT (owner 09-20: the job belongs in the NAME PREFIX, a label floating at the shoulder is hard to read): team b_<Name>, aqua,
# prefix "[<job>] " written by the dispatcher through rcon (bots/army/dispatcher.js labelPass). Who is a bot is decided by the pid score, not by a team.
node $W/bots/rcon.js "kill @e[type=text_display,tag=jl]" >/dev/null
for n in $(node -e "console.log(Object.keys(require('$W/bots/assignments.json')).join(' '))"); do
  node $W/bots/rcon.js "team add b_$n" "team modify b_$n color aqua" "team modify b_$n friendlyFire false" "team modify b_$n collisionRule never" "team join b_$n $n" >/dev/null
done
node $W/bots/rcon.js "team remove army" >/dev/null
node $W/bots/rcon.js "datapack list enabled" "scoreboard objectives list" | cut -c1-220
grep -a "modes\|Failed to load\|Couldn't parse\|Parsing error" $S/logs/latest.log | tail -8 | cut -c1-300
